### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by ANKITy102** [tenzopy/codeIt#104]
I would like to develop a Snake game and incorporate it into this repository. The game will display the player's score as well as the highest score achieved in previous games.
Tech Stack will be Html, CSS, JavaScript.

 Could you kindly assign this issue to me?

**Comment by vismaya2002** [comment]
Create a separate folder in the current web folder and proceed.
Make sure you read the guidelines before proceeding.

**Comment by Jagdeep30** [comment]
Is it still open to contribute?
I can contribute using React js

**Comment by vismaya2002** [comment]
@Jagdeep30 Its already assigned.
You can create another issue by the way.

**Comment by Jagdeep30** [comment]
@vismaya2002   For same programe?

**Comment by vismaya2002** [comment]
OK..you can create a new issue for the same using React.js @Jagdeep30
