### ISSUE TITLE
Github user search

### ISSUE THREAD

**Issue by capsy14** [tenzopy/codeIt#108]
I want to work on the development of a GitHub user search feature. My objective is to incorporate this feature into our repository, enabling it to display a user's name, location, and follower count upon entering a GitHub username. I intend to implement this feature using HTML , CSS and Javascript .
Please assign this issue to me :)

**Comment by vismaya2002** [comment]
Create a separate folder in the current web folder and proceed.
Make sure you read the guidelines before proceeding.
