### ISSUE TITLE
Pattern Printing java

### ISSUE THREAD

**Issue by sr2005roy** [tenzopy/codeIt#110]
I would like to add Open Pyramid Pattern printing codes in java language :)

**Comment by sr2005roy** [comment]
I am ready with the code please assign me

**Comment by vismaya2002** [comment]
You can only add one file per PR

**Comment by sr2005roy** [comment]
yes only one file of java will be added

**Comment by sr2005roy** [comment]
please assign this issue to me.

**Comment by vismaya2002** [comment]
Go ahead.

**Comment by sr2005roy** [comment]
sorry mistakenly I had committed 2 files in my last PR
I have made a file which prints diamond 
![image](https://github.com/tenzopy/codeIt/assets/122456380/09648370-d33a-4fde-a8b0-e0057ebc444e)
![image](https://github.com/tenzopy/codeIt/assets/122456380/7825ba05-1cf5-498a-a909-f8d96dc539d7)
Hope you like:)
