### ISSUE TITLE
Fibonacci series upto N numbers using java

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#115]
Implement a java program to print the Fibonacci series upto N numbers using java in java folder.

**Comment by Jagdeep30** [comment]
Assign this to me. I can do this

**Comment by vismaya2002** [comment]
Make sure to read the guidelines and proceed.
Give a description for your PR also.

**Comment by Jagdeep30** [comment]
should i create a separate branch?

**Comment by vismaya2002** [comment]
Not necessarily.
