### ISSUE TITLE
Music Player - Web Application like Spotify

### ISSUE THREAD

**Issue by ANKITy102** [tenzopy/codeIt#117]
I would like to develop a Music Player Web Application and contribute it to this repository.

The application will include a music player with controls for playing the next and previous tracks. Users will also have the ability to skip forward or backward within a song. In addition, the application will feature a bottom bar that displays the current playing song and its progress.

Please assign this issue to me.

**Comment by vismaya2002** [comment]
Please mention the stacks you are going to use to develop this.

**Comment by ANKITy102** [comment]
@vismaya2002 
I will use HTML, CSS, JavaScript

**Comment by vismaya2002** [comment]
@ANKITy102 Make a folder inside the web folder. Proceed
