### ISSUE TITLE
Snake Game in React

### ISSUE THREAD

**Issue by Jagdeep30** [tenzopy/codeIt#128]
Create a react app of basic snake game.

**Comment by Jagdeep30** [comment]
Assign this to me. I can do.

**Comment by vismaya2002** [comment]
Yes you can proceed.
Go through the guidelines also.

**Comment by Jagdeep30** [comment]
please also review the fibonacci number pull request

**Comment by vismaya2002** [comment]
Of course, we are  going through each requests.

**Comment by Jagdeep30** [comment]
Snake game to be included in Web folder or Javascript one?

**Comment by vismaya2002** [comment]
Include in javascript folder.
