### ISSUE TITLE
Modify the prime.py file  using definition in Python.

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#13]
Implement  the prime.py  program in python folder to check whether the number is prime or not, using definition in Python.

**Comment by thezeeshann** [comment]
@vismaya2002 assign me.

**Comment by vismaya2002** [comment]
@thezeeshann yes, you can work on it.

**Comment by Aman5989** [comment]
assign me

**Comment by vismaya2002** [comment]
@Aman5989 Create a new issue which you want to work on, as this is assigned already.

**Comment by Aman5989** [comment]
sure!
