### ISSUE TITLE
Selection sort using Java

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#130]
Implement selection sort using Java in java folder.

**Comment by avinashkrishna07** [comment]
Hii @vismaya2002 Kindly assign this issue to me, as I'm interested in this.
Thank you!

**Comment by prabhatotato** [comment]
I got this if u let me.

**Comment by vismaya2002** [comment]
@avinashkrishna07 Can proceed.

**Comment by vismaya2002** [comment]
@prabhatotato You can create another issue.

**Comment by avinashkrishna07** [comment]
@vismaya2002 already did it in #129
