### ISSUE TITLE
Calculate LCM

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#132]
Implement a Kotlin program to calculate the LCM of two numbers in kotlin folder.

**Comment by fvaysh** [comment]
I have already forked and written the code as required, please assign me this issue so I can commit the changes.

**Comment by vismaya2002** [comment]
@prabhatotato you can proceed after reading the guidelines.

**Comment by vismaya2002** [comment]
@fvaysh Assignment is based on first come first serve. 
You could have mentioned here. 
Please make another issue
