### ISSUE TITLE
Update the README.md of each works in the web folder

### ISSUE THREAD

**Issue by akkupy** [tenzopy/codeIt#155]
@umeshSinghVerma @BikramNarayan @capsy14 @ANKITy102 @Siddhesh179 

Objective is to implement a README.md in your respective work folders regarding what your project is what it does and some sample images/screenshots.
Note : People mentioned here should add the README in their respective folders..

**Comment by Alphaviper7769** [comment]
I can do this please assign it to me

**Comment by akkupy** [comment]
@Alphaviper7769 The work is for the people I mentioned! Read the description again..

If you are ready to test out all their work and create README for each folders then I can assign it to you..

**Comment by akkupy** [comment]
@Alphaviper7769 U can proceed ...but you should create the README in each folder within the web folder


Reply on this issue if you have any doubts

**Comment by umeshSinghVerma** [comment]
> @umeshSinghVerma @BikramNarayan @capsy14 @ANKITy102 @Siddhesh179
> 
> Objective is to implement a README.md in your respective work folders regarding what your project is what it does and some sample images/screenshots. Note : People mentioned here should add the README in their respective folders..

I will try add the instructions how to use my components in the readme.md :)

**Comment by Siddhesh179** [comment]
am i still allowed to edit the readme file inside the web folder?

**Comment by Siddhesh179** [comment]
Sent a PR please close this issue!

**Comment by akkupy** [comment]
@Siddhesh179 You can edit the top level README file,,,the one within the web folder..Refer the C folder README.md and makes the changes according to that..

**Comment by Alphaviper7769** [comment]
I have added 4 readme files to projects. Please refer #208 and merge it if it is okay.
Thanks
