### ISSUE TITLE
Build a tree object from a list of objects adopting a nesting concept.

### ISSUE THREAD

**Issue by acf-patrick** [tenzopy/codeIt#166]
# Overview
We want to convert a plain array of nodes to a nested data structure. 
# Problem Statement
A list of folder paths could be used as trivial examples :
From ["/home", "/usr/include", "/home/acf", "/usr/lib/SDL",  "/usr", "/src", "/home/acf/tree"], we should get :
```
/src

/usr
|__ /usr/include
|__ /usr/lib/SDL

/home
|__ /home/acf
    |__ /home/acf/tree
```
# Proposed Solution
Let's encapsulate our solution into a class ```TreeNode``` symbolizing a node. We have to combine nodes until we reach leaves 🍂

**Comment by acf-patrick** [comment]
Can you assign this to me ? I would like to share my C++ implementation for this problem

**Comment by vismaya2002** [comment]
@acf-patrick You should have gone through the guidelines first before  commiting.
