### ISSUE TITLE
Add Hero Section to Component Folder

### ISSUE THREAD

**Issue by umeshSinghVerma** [tenzopy/codeIt#174]
**Title:** Add Hero Section to Component Folder

**Description:**
We need to enhance our application's user interface by adding a hero section to the component folder. A hero section is a visually appealing and informative element often placed at the top of a webpage to capture users' attention and provide important information or a call to action.

**Scope:**
This issue will involve creating a new component or modifying an existing one to implement the hero section. The hero section should be designed in a way that makes it easy to customize its content and appearance according to specific page requirements.

**Tasks:**
1. Create a new component for the hero section, or identify an existing component that can be modified for this purpose.
2. Design the hero section with attention to visual aesthetics and user experience.
3. Ensure the hero section is responsive and adapts well to different screen sizes and devices.
4. Implement the necessary logic and data bindings to dynamically update the hero section's content as needed.
5. Add appropriate documentation and comments to the code for future reference and maintenance.

**Acceptance Criteria:**
- The hero section component is successfully created or modified and added to the component folder.
- The hero section is visually appealing and aligns with our application's design guidelines.
- The hero section is responsive and works well on various screen sizes.
- The hero section can be easily customized with different content and styles.

**Additional Information:**
Please ensure that this change does not introduce any breaking changes to the existing codebase, and thorough testing should be conducted to validate its functionality.

**Comment by umeshSinghVerma** [comment]
**Update:**
I have developed a sample hero section component, and I've attached screenshots below to showcase its appearance and functionality. 

Screenshot in desktop view
![image](https://github.com/tenzopy/codeIt/assets/119877487/52389435-adb3-485a-a374-6be912a19778)

Screenshot in mobile view
![image](https://github.com/tenzopy/codeIt/assets/119877487/a6a4326c-9eec-4c18-8c46-b482e77f2450)


I believe the component meets the criteria outlined in the issue description. If there are any specific aspects or improvements you'd like to discuss, please feel free to provide feedback. 

If everything looks good, could you please assign this issue to me? I'm ready to continue working on it and ensure its successful completion.

**Comment by vismaya2002** [comment]
@umeshSinghVerma Nice, you can proceed.
