### ISSUE TITLE
Add Light/Dark Mode Toggle Component

### ISSUE THREAD

**Issue by umeshSinghVerma** [tenzopy/codeIt#176]
**Description:**
We need to enhance the user experience of our website by implementing a light/dark mode toggle component. This feature will allow users to switch between light and dark themes, providing them with a more comfortable viewing experience based on their preferences.

**Scope:**
This issue involves creating a new component responsible for toggling between light and dark modes. The component should seamlessly switch the website's theme, adjusting colors, and other visual elements accordingly.

**Tasks:**
1. Develop a new component responsible for toggling light and dark modes.
2. Implement functionality to switch between the two themes.
3. Ensure that the theme change is smooth and visually appealing.
4. Make sure the selected theme preference is saved and persistent across sessions.
5. Add appropriate documentation and comments for future maintenance.

**Acceptance Criteria:**
- A new light/dark mode toggle component is successfully created.
- Users can switch between light and dark modes effortlessly.
- The theme change is visually appealing and easy to understand.
- The selected theme preference is saved and persistent for returning users.
- The code includes thorough documentation and comments.

**Additional Information:**
This feature will significantly improve the user experience of our website by giving users control over their preferred viewing theme. 

Could you please assign this task to me? I'm eager to work on this and contribute to enhancing our website's usability and visual appeal with the light/dark mode toggle component.

**Comment by vismaya2002** [comment]
You can proceed.
