### ISSUE TITLE
Add Shopping List React App

### ISSUE THREAD

**Issue by Ved091** [tenzopy/codeIt#198]
**Overview**
We can add a shopping List App in which anyone can store their day to day items.
**Problem Statement** 
There is a problem to list all the data on a paper which can cause problem is the paper went missing. 
**Proposed Solution**
This Shopping List App will take care of maintaining the data of the user and the user can easily add and delete the items

**Comment by akkupy** [comment]
Rename the Issue Title as per guideline

**Comment by akkupy** [comment]
Proceed
