### ISSUE TITLE
[UPDATE] Java Folder README.md

### ISSUE THREAD

**Issue by akkupy** [tenzopy/codeIt#206]
Update the table in the java folder README.md with the details of all the programs present in the folder.

**Comment by antriksh-9** [comment]
Hey @akkupy I want to work on this issue.
Please assign it to me.

**Comment by vismaya2002** [comment]
@antriksh-9 Ok proceed.
Stick on to the guidelines.

**Comment by bharathgaddam1712** [comment]
Can you assign me this issue
