### ISSUE TITLE
[cpp]3_Sum_Problem

### ISSUE THREAD

**Issue by vaibhav211002** [tenzopy/codeIt#207]
3Sum Problem

Given an array of integers nums, find all unique triplets in the array that sum up to a target value target. Each triplet should be represented as an array of three integers.

You must not use the same element twice in a triplet.

Input:
An array of integers nums (length n, 3 <= n <= 1000).
An integer target (-10^9 <= target <= 10^9).
Output:
A list of unique triplets that sum up to the target value. Each triplet should be sorted in ascending order and should not contain duplicate triplets.

Approach : 

Approach:

Sort the input array in ascending order.
Use a two-pointer approach to find triplets that sum to zero while avoiding duplicates.
Return the unique triplets found.

Time Complexity:  O(n^2), where n is the number of elements in the input array  .

Space Complexity: O(k), where k is the number of unique triplets found.

Please assign this issue to me .

**Comment by akkupy** [comment]
Change Title According to Guideline and You will be assigned.

**Comment by akkupy** [comment]
Proceed and stick to the guidelines
