### ISSUE TITLE
[JAVA] Infix To Postfix Algorithm

### ISSUE THREAD

**Issue by cherindranathreddy** [tenzopy/codeIt#210]
**Overview**
**Infix expression:** 
The expression of the form “a operator b” (a + b) i.e., when an operator is in-between every pair of operands. 
**Postfix expression:** 
The expression of the form “a b operator” (ab+) i.e., When every pair of operands is followed by an operator.

**Problem Statement**
Write a program to convert an Infix expression to Postfix form.

**Proposed Solution**
Here are the steps of the algorithm to convert Infix to postfix using stack :
  1) Scan all the symbols one by one from left to right in the given Infix Expression.
  2) If the reading symbol is an operand, then immediately append it to the Postfix Expression.
  3) If the reading symbol is left parenthesis ‘( ‘, then Push it onto the Stack.
  4) If the reading symbol is right parenthesis ‘)’, then Pop all the contents of the stack until the respective left parenthesis is popped and append each popped symbol to Postfix Expression.
  5) If the reading symbol is an operator (+, –, *, /), then Push it onto the Stack. However, first, pop the operators which are already on the stack that have higher or equal precedence than the current operator and append them to the postfix. If an open parenthesis is there on top of the stack then push the operator into the stack.
  6) If the input is over, pop all the remaining symbols from the stack and append them to the postfix.

**Comment by akkupy** [comment]
Proceed..Stick to the Guidelines on creating a PR
