### ISSUE TITLE
[CPP] Detecting Cycles in an Undirected Graph 

### ISSUE THREAD

**Issue by vaibhav211002** [tenzopy/codeIt#213]
Problem Statement:

Title: Detecting Cycles in an Undirected Graph

You are given a set of undirected edges that represent a graph. Your task is to write a program that can detect whether the graph contains any cycles or not.

Input:

An integer n (1 ≤ n ≤ 1000), representing the number of vertices in the graph.
A list of m undirected edges, where each edge is represented as a pair of integers u and v (0 ≤ u, v < n), indicating an edge between vertex u and vertex v. The list of edges is provided as input.
Output:

If the graph contains at least one cycle, output "it is cyclic."
If the graph is acyclic (no cycles present), output "it is not cyclic."

Approach:

The program detects cycles in the given graph using depth-first search (DFS). Here's an overview of the approach:
Create an adjacency list representation of the graph based on the input edges.
Initialize a map to keep track of visited vertices and set them all as "not visited."
Iterate through each vertex in the graph.
For each unvisited vertex, start a DFS traversal. During the traversal, mark visited vertices and keep track of their parent vertex.
If a vertex is visited again during the traversal and it's not the parent of the current vertex (i.e., there's a back edge to a previously visited vertex), then a cycle is detected, and the program prints "it is cyclic."
If the traversal completes for all vertices without finding any cycles, the program prints "it is not cyclic."

**Comment by akkupy** [comment]
Change the issue title as per guideline

**Comment by vismaya2002** [comment]
@vaibhav211002 You can proceed.
