### ISSUE TITLE
[JAVA] Postfix to Infix Algorithm

### ISSUE THREAD

**Issue by cherindranathreddy** [tenzopy/codeIt#216]
**Overview**
Infix expression:
The expression of the form “a operator b” (a + b) i.e., when an operator is in-between every pair of operands.
Postfix expression:
The expression of the form “a b operator” (ab+) i.e., When every pair of operands is followed by an operator.

**Problem Statement**
Write a program to convert an Postfix expression to Infix form.

**Proposed Solution**
Here are the steps of the algorithm to convert postfix to Infix using stack :
  1) Scan all symbols one by one from left to right in the given postfix expression .
  2) If the reading symbol is an operand , push it into the stack .
  3) If the reading symbol is an operator , then a. Pop two expression from the stack , operand1 and operand2 , which is operand for the current operator b. Push “(“ + operand2 + operator + operand1 + “)” into the stack
  4) If there is no symbol left then stop the process . Top of the stack will have the required infix expression .

**Comment by cherindranathreddy** [comment]
@akkupy can you assign this issue to me?

**Comment by cherindranathreddy** [comment]
@vismaya2002 updated the title

**Comment by vismaya2002** [comment]
@cherindranathreddy You can proceed.
