### ISSUE TITLE
 Fix the file leap.py in python folder.

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#23]
Complete the leap.py file for checking if an year is leap or not with neat and correct code in Python language.

**Comment by Ash0069** [comment]
hey @vismaya2002 i created a pull request for this issue

**Comment by vismaya2002** [comment]
@Ash0069 Add a correct description for the PR.

**Comment by Ash0069** [comment]
I just did

**Comment by Ash0069** [comment]
@akkupy
