### ISSUE TITLE
[C] implement FCFS program using C

### ISSUE THREAD

**Issue by AniruddhaGawali** [tenzopy/codeIt#236]
as per the [issue in #201](https://github.com/tenzopy/codeIt/issues/201#issuecomment-1745380227)

### Overview
create a FCFS secluding program using c

### Problem Statement
Develop a C program that simulates FCFS scheduling for a set of processes. Each process is characterized by a unique Process ID (PID), Arrival Time (AT), and Burst Time (BT). The program should calculate and display the completion time for each process and the order in which they are scheduled.

### Solution
- create a FCFS program file using c folder
- create a process struct
- create function to calculate: Arrival Time, Burst Time, Completion Time, Turnaround, Time Waiting Time
- Calculate the following for each process:
    - Completion Time (CT): The time at which the process completes its execution.
    - Turnaround Time (TAT): The total time taken from arrival to completion for each process (TAT = CT - AT).
    - Waiting Time (WT): The time the process spends waiting in the ready queue (WT = TAT - BT).

**Comment by AniruddhaGawali** [comment]
btw, i have code of this can you assigned it to me

**Comment by akkupy** [comment]
Proceed
