### ISSUE TITLE
Create Palindrome.cpp in C++ folder

### ISSUE THREAD

**Issue by Aman5989** [tenzopy/codeIt#24]
Create a program in cpp to check a given number is Palindrome or not.

**Comment by Aman5989** [comment]
assign me

**Comment by akkupy** [comment]
Create a short description too.. what the program does etc as per the guidelines

**Comment by Aman5989** [comment]
added

**Comment by akkupy** [comment]
Mention this issue id on the PR too

**Comment by Aman5989** [comment]
added that one too
