### ISSUE TITLE
Add Insertion Sort Algo in Python

### ISSUE THREAD

**Issue by Aman5989** [tenzopy/codeIt#27]
Create a program in python to implement insertion sorting

**Comment by Aman5989** [comment]
Assign me

**Comment by vismaya2002** [comment]
Go through the guidelines and proceed.

**Comment by Aman5989** [comment]
added description

**Comment by Ash0069** [comment]
please assign me this issue

**Comment by vismaya2002** [comment]
@Ash0069 Please create a new issue.
