### ISSUE TITLE
Edit the README.md in C folder

### ISSUE THREAD

**Issue by akkupy** [tenzopy/codeIt#37]
* It should contain a description of the files  present and a link to each file in a table format.
*  Add a new Section indicating the usage of the folder ( For adding new programs and editing existing programs for errors).
*  Make the README.md informative and readble.

**Comment by vismaya2002** [comment]
@akadeepesh Yes , do it according to the instructions given.

**Comment by akadeepesh** [comment]
can't do it now

**Comment by 100godmoon** [comment]
please assign this to me .

**Comment by vismaya2002** [comment]
@100godmoon Yes, you can proceed after reading the instructions given.
