### ISSUE TITLE
Letter Combinations of a Phone Number

### ISSUE THREAD

**Issue by Aman5989** [tenzopy/codeIt#38]
Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.

A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.

Example 1:

Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]
Example 2:

Input: digits = ""
Output: []
Example 3:

Input: digits = "2"
Output: ["a","b","c"]

**Comment by vismaya2002** [comment]
@Aman5989 Yes proceed.
