### ISSUE TITLE
Edit the README.md in cpp folder

### ISSUE THREAD

**Issue by akkupy** [tenzopy/codeIt#42]
It should contain a description of the files present and a link to each file in a table format.

Add a new Section indicating the usage of the folder ( For adding new programs and editing existing programs for errors).

Make the README.md informative and readable.

**Comment by 100godmoon** [comment]
please assign me this

**Comment by akkupy** [comment]
@100godmoon Proceed!

**Comment by 100godmoon** [comment]
can you please elaborate this a little bit more
"Add a new Section indicating the usage of the folder ( For adding new programs and editing existing programs for errors)."
