### ISSUE TITLE
Edit the README.md in java folder

### ISSUE THREAD

**Issue by akkupy** [tenzopy/codeIt#43]
It should contain a description of the files present and a link to each file in a table format.

Add a new Section indicating the usage of the folder ( For adding new programs and editing existing programs for errors).

Make the README.md informative and readable.

**Comment by 100godmoon** [comment]
can i work on this ?

**Comment by vismaya2002** [comment]
@100godmoon Yes, you can proceed.

**Comment by prabhatotato** [comment]
assign this to me

**Comment by prabhatotato** [comment]
please assign this to me. I want to contribute to this.

**Comment by vismaya2002** [comment]
@prabhatotato You can proceed.
