### ISSUE TITLE
Add implementation of BFS and DFS in python

### ISSUE THREAD

**Issue by Niyati3031** [tenzopy/codeIt#46]
Can you assign this to me for hacktoberfest 2023

**Comment by akkupy** [comment]
Create a short description about the work you are doing..

Link this issue to the PR you are creating.

Only one file is  allowed to merge.

Check Guidelines.

**Comment by Niyati3031** [comment]
Then can I add just BFS?

**Comment by akkupy** [comment]
Yes! DFS can be added as next PR
