### ISSUE TITLE
Finding product of two numbers using c#

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#51]
Implement a C# program to find product of two numbers using recursion and upload it to c# folder

**Comment by Mohitraut07** [comment]
I want to try this, also I am a front-end developer, please let me know if you require my skills.

**Comment by vismaya2002** [comment]
@Mohitraut07 Yes, you can proceed by providing a description of the PR.

**Comment by Siddhesh179** [comment]
can i also contribute to this issue?

**Comment by akkupy** [comment]
@Siddhesh179 Create another issue .This is assigned to @Mohitraut07

**Comment by Mohitraut07** [comment]
@vismaya2002 and @akkupy I have submitted the PR, and got it done early as I was previously working on it, please review.
