### ISSUE TITLE
Complete ascending.java in java folder

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#54]
Implement a java program to arrange the elements of array in ascending.java  in ascending order. Array is already given.

**Comment by Siddhesh179** [comment]
can you please assign this task to me?

**Comment by vismaya2002** [comment]
@Siddhesh179 Yes you can proceed by providing a description of the PR.

**Comment by hiabhi-cpu** [comment]
> Implement a java program to arrange the elements of array in ascending.java in ascending order. Array is already given.

Which sort technic to use in sorting??

**Comment by Siddhesh179** [comment]
can you please assgin me now as I will solve it immediately? please

**Comment by Siddhesh179** [comment]
please merge the pr as i have already completed this issue.
