### ISSUE TITLE
Implement merge sort in C

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#63]
Implement  a  program  for merge sort in C.

**Comment by Mohitraut07** [comment]
i want to try.

**Comment by Virtual4087** [comment]
Can i work on this?

**Comment by prabhatotato** [comment]
please assign this to me.

**Comment by adarsh3002** [comment]
Assign to me .I can implement Merge Sort in C for efficient array sorting using a divide-and-conquer approach

**Comment by vismaya2002** [comment]
@Mohitraut07 You can proceed.

**Comment by vismaya2002** [comment]
@prabhatotato You can create another issue.

**Comment by pawan8120** [comment]
can you pleasse assign it to me as i m doing compitative rpogramming from last 2 years here are my profile of codeforces https://codeforces.com/profile/pawan_8120 , codechef https://www.codechef.com/users/pawan_8120 , https://cses.fi/user/126394 ,

**Comment by vismaya2002** [comment]
@adarsh3002 and @pawan8120  You can make another issues.
