### ISSUE TITLE
Write Linked List code in C and  add linked list functions

### ISSUE THREAD

**Issue by 100godmoon** [tenzopy/codeIt#69]
Can i write a code in C to create a Linked list .
I also want to add some functions that operates on a linked list
example : display linked list , Cycle in linked list etc

**Comment by pawan8120** [comment]
can you pleasse assign it to me as i m doing compitative rpogramming from last 2 years here are my profile of codeforces https://codeforces.com/profile/pawan_8120 , codechef https://www.codechef.com/users/pawan_8120 , https://cses.fi/user/126394 ,

**Comment by pawan8120** [comment]
can you bit more elaborate about problem statement

**Comment by pawan8120** [comment]
ok i will add as many funtion i can

**Comment by pawan8120** [comment]
i have alredy complete this just need to push

**Comment by 100godmoon** [comment]
you can proceed, but merging your pr is not in my hands as i am not the maintainer of the repository.

**Comment by vismaya2002** [comment]
@100godmoon You can proceed.

**Comment by akkupy** [comment]
@pawan8120 This issue was created by @100godmoon so he will be assigned..

**Comment by vismaya2002** [comment]
@pawan8120 Please, make another issue .

**Comment by pawan8120** [comment]
ok ,i try another issue
