### ISSUE TITLE
A CLI app using javascript 

### ISSUE THREAD

**Issue by Mohitraut07** [tenzopy/codeIt#70]
An app to quiz your friends on their favourite sitcom F.R.I.E.N.D.S .

**Comment by Mohitraut07** [comment]
Can I add this to javascript folder

**Comment by Mohitraut07** [comment]
https://www.w3docs.com/snippets/git/how-to-import-multiple-projects-into-a-single-git-repository.html Will this work?

**Comment by akkupy** [comment]
I just asked you to if you are adding a single js file or a folder of files.?
