### ISSUE TITLE
Incorporate All Sorting Techniques in 'C++' Folder

### ISSUE THREAD

**Issue by BikramNarayan** [tenzopy/codeIt#72]
May I request to add all sorting techniques to the 'C++' folder? I'd like to take ownership of this issue and contribute the necessary code.

**Comment by vismaya2002** [comment]
@BikramNarayan You can add only a single sorting technique. If you agree with this , please mention which sorting technique you are going to implement

**Comment by BikramNarayan** [comment]
I want to add Insertion sort technique

**Comment by capsy14** [comment]
@vismaya2002 I want to add merge sort technique.

**Comment by vismaya2002** [comment]
@capsy14 Specify In which language you wish to add the code.
