### ISSUE TITLE
Web Development - Landing Page

### ISSUE THREAD

**Issue by BikramNarayan** [tenzopy/codeIt#79]
I want create a responsive landing page using React. This landing page will provide information about various programming languages along with their descriptions. Can i do that?

**Comment by vismaya2002** [comment]
@BikramNarayan  Please, specify the file structure.

**Comment by BikramNarayan** [comment]
codeIt/
  └── web/
      └── React/

I will create a 'React' folder within the 'web' directory, aligning with the standard file structure for React web applications. This 'React' folder will house the code for the responsive landing page, which will provide information about various programming languages and their descriptions.

**Comment by akkupy** [comment]
Should note that the PR MUST be within the Guidelines..
Currently one file per PR is only accepted

**Comment by BikramNarayan** [comment]
Got it! I'll follow the guidelines. I'll create a single HTML file in the existing 'web' folder with information about all programming languages and their descriptions.

**Comment by vismaya2002** [comment]
Go ahead...

**Comment by akkupy** [comment]
Use a readable name for your html file also...if you want to add css or js...create a new folder within the web folder and can add html+css+js
