### ISSUE TITLE
One Hot Encoding for categorical dataset

### ISSUE THREAD

**Issue by Prisha-baveja** [tenzopy/codeIt#83]
I want to add a model which implements One Hot Encoding on a categorical dataset into a Jupyter notebook folder. One Hot Encoding is a basis for conversion of categorical data to numerical (vector representation).

**Comment by akkupy** [comment]
Currently the repo is restricted to 1 file per PR...
Can you specify the file structure and do you have a dataset that needs to be uploaded?

**Comment by Prisha-baveja** [comment]
Can you please assign it to me, so that I can start working on it.

**Comment by Prisha-baveja** [comment]
I have a sample dataset which has one hot encoding implemented on it. The user can customise this dataset as per their on requirements.

**Comment by Prisha-baveja** [comment]
The file structure would be a ipynb, that a python notebook

**Comment by akkupy** [comment]
Work can be assigned once you specify the folder structure prior to starting the work..

If PR do not meet the guidelines it will be considered as invalid

**Comment by akkupy** [comment]
@Prisha-baveja a single file only?

**Comment by Prisha-baveja** [comment]
Yes, it is a single file only.

**Comment by akkupy** [comment]
Proceed
