### ISSUE TITLE
Pattern Printing c++

### ISSUE THREAD

**Issue by sr2005roy** [tenzopy/codeIt#84]
I would like to add different pattern printing codes in a folder in c++ language

**Comment by akkupy** [comment]
Only one file per PR is allowed..specify the pattern in the issue prior to assignment of the issue

**Comment by sr2005roy** [comment]
what about an open pyramid?
<img width="125" alt="image" src="https://github.com/tenzopy/codeIt/assets/122456380/e9659dd4-42f2-42d9-92f8-e896f007a913">
for input 5

**Comment by akkupy** [comment]
Proceed with open pyramid!

**Comment by sr2005roy** [comment]
I have made the pull request for this issue 
the output from the code:
![image](https://github.com/tenzopy/codeIt/assets/122456380/25c71148-f525-48e7-ae12-3431ca6124b8)
![image](https://github.com/tenzopy/codeIt/assets/122456380/27e5f433-7abb-4b82-ba69-52360d774851)
please check and merge :)
