### ISSUE TITLE
Pattern Printing c

### ISSUE THREAD

**Issue by sr2005roy** [tenzopy/codeIt#85]
I would like to add different pattern printing codes in a folder in c language

**Comment by akkupy** [comment]
Only one file per PR is allowed.Specify the pattern and problem statement

**Comment by sr2005roy** [comment]
what about an open pyramid?
![Uploading image.png…]()

for input 5

**Comment by akkupy** [comment]
Proceed...
And check the guidelines too before making a PR

**Comment by sr2005roy** [comment]
I have made the pull request for this issue
the output from the code:
![image](https://github.com/tenzopy/codeIt/assets/122456380/0826c4aa-1252-4945-bca8-01b301d84b47)
![image](https://github.com/tenzopy/codeIt/assets/122456380/99f05df8-70c7-477c-8295-5c9729c31375)
please check and merge :)
