### ISSUE TITLE
Component Library for Web Development 

### ISSUE THREAD

**Issue by umeshSinghVerma** [tenzopy/codeIt#88]
There should be a folder inside the web folder which contains the necessary components essential for making basic web apps. If it seems feasible then please assign it to me

**Comment by akkupy** [comment]
Elaborate your work...this web folder only accepts One file per PR..

**Comment by umeshSinghVerma** [comment]
I intend to create separate pull requests for individual components, such as the Header Component in one PR, the Footer Component in another PR, and so on
