### ISSUE TITLE
Contribute Sieve Of Eratosthenes program in c++

### ISSUE THREAD

**Issue by Akash7649** [tenzopy/codeIt#92]
Hey I would like to contribute the program of Sieve Of Eratosthenes program in C++, which finds all the prime numbers in (n*log(log(n))) time complexity so please assign me this issue under the tag of Hacktoberfest2023

**Comment by akkupy** [comment]
Code should meet the Guidelines too..Proceed

**Comment by pawan8120** [comment]
can you assign this issue to me ?
