### ISSUE TITLE
Correct the code in mergeSort.c in c folder

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#93]
Fix the issue in merge sort algorithm in mergeSort.c

**Comment by sr2005roy** [comment]
what exactly you want an input of array size and array??

**Comment by avinashkrishna07** [comment]
Hii @vismaya2002 Can you please assign this to me, as i'm interested and would like to contribute on this project.
Thank you!

**Comment by vismaya2002** [comment]
@avinashkrishna07 Yes, you can proceed. Provide a description for the PR.

**Comment by pawan8120** [comment]
can you assign this issue to me ?
