### ISSUE TITLE
C# program to add two matrices.

### ISSUE THREAD

**Issue by vismaya2002** [tenzopy/codeIt#99]
Implement a C# program to add two matrices.

**Comment by abhi-2010** [comment]
for (int i = 0; i < rows; i++)
        {
            for (int j = 0; j < cols; j++)
            {
                sumMatrix[i, j] = matrix1[i, j] + matrix2[i, j];
            }
        }

//martix1 and matrix2 are ur matrices and sumMatrix is result

**Comment by vismaya2002** [comment]
You can proceed. Provide description for PR and make sure you read the guidelines.
